# Generated by Django 5.0.2 on 2024-02-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Details',
            fields=[
                ('chapters_name', models.CharField(max_length=50)),
                ('book_name', models.CharField(max_length=25)),
                ('author', models.CharField(max_length=30)),
                ('pages', models.IntegerField()),
                ('year', models.IntegerField()),
                ('Book_serial_no', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
